### ISSUE TITLE
Illum files are now .npy, not .mat

### ISSUE THREAD

**Issue by bethac07** [broadinstitute/pe2loaddata#12]

**Comment by bethac07** [comment]
@shntnu I was going to just do this, but before I do- right now, '.mat' is hard coded.  Do we want to hardcode '.npy' instead, or pass it configurably?

**Comment by shntnu** [comment]
I'd go with configurably, given that it isn't too hard to do so
So maybe `--illum-extn` with default = `npy`?

**Comment by bethac07** [comment]
Do we want default = `npy` (more convenient for us going forward) or default = `mat` (retains compatibility for anyone else using this)? Do we think anyone but us is using this?

**Comment by shntnu** [comment]
indeed, default `npy` is the way to go but more because of the move to CP3. 

Just in case someone is using,  we can indicate this in the README (ideally we'd have a changelog, but this isn't really being maintained as a package)
