### ISSUE TITLE
'ChannelName' output, no error, XML file compatibility issue

### ISSUE THREAD

**Issue by jenna-tomkinson** [broadinstitute/pe2loaddata#34]
# Problem

I am trying to create a LoadData CSV with an Index.xml file (I had to rename it to get the error that it wasn't named Index.idx.xml), but I am getting a weird output where it only gives 'ChannelName' over and over and then a blank CSV file.

Here is what my config file has for channels (I have triple-checked it that the spelling of the channel names are correct):
```
channels:
    HOECHST 33342: OrigDNA
    Alexa 568: OrigAGP
    Alexa 647: OrigMito
    Alexa 488: OrigER
    Alexa 488 Long (CP): OrigRNA
    Brightfield high: OrigBrightfield
```
The output from running the function only yields 'ChannelName' over thousands of lines.
![image](https://github.com/user-attachments/assets/82703d19-2cc4-47cb-ad02-63e62cb182ea)

GitHub won't let me upload the XML file. I feel that something is wrong with the file as I have been able to use this with a different dataset, and it is completely fine.

I would appreciate any ideas on why this output is happening and no error? Also, will PR #33 be merged in, as that would solve the first error that I was getting since my files are named `Index.xml`?

**Comment by jenna-tomkinson** [comment]
My current running theory is that "ChannelName" is missing for each of the images in the XML file I am using.

Here is the XML data for one image in my **current XML file**:

```
    </Image>
    <Image Version="1">
      <id>1422K1F9P1R5</id>
      <State>Ok</State>
      <URL>r14c22f09p01-ch5sk1fk1fl1.tiff</URL>
      <Row>14</Row>
      <Col>22</Col>
      <FieldID>9</FieldID>
      <PlaneID>1</PlaneID>
      <TimepointID>1</TimepointID>
      <SequenceID>1</SequenceID>
      <GroupID>1</GroupID>
      <ChannelID>5</ChannelID>
      <FlimID>1</FlimID>
      <PositionX Unit="m">0.000645814</PositionX>
      <PositionY Unit="m">-0.000645814</PositionY>
      <PositionZ Unit="m">-6E-06</PositionZ>
      <AbsPositionZ Unit="m">0.134374306</AbsPositionZ>
      <MeasurementTimeOffset Unit="s">0</MeasurementTimeOffset>
      <AbsTime>2024-07-04T17:46:22.7896169-04:00</AbsTime>
```

Here is the XML data for an image in the XML file for a dataset **that does work**:

```
    </Image>
    <Image Version="1">
      <id>1612K1F4P5R3</id>
      <State>Ok</State>
      <URL>r16c12f04p05-ch3sk1fk1fl1.tiff</URL>
      <Row>16</Row>
      <Col>12</Col>
      <FieldID>4</FieldID>
      <PlaneID>5</PlaneID>
      <TimepointID>0</TimepointID>
      <ChannelID>3</ChannelID>
      <FlimID>1</FlimID>
      <ChannelName>Alexa 700_narrow</ChannelName>
      <ImageType>Signal</ImageType>
      <AcquisitionType>NonConfocal</AcquisitionType>
      <IlluminationType>Epifluorescence</IlluminationType>
      <ChannelType>Fluorescence</ChannelType>
      <ImageResolutionX Unit="m">2.9898804047838085E-07</ImageResolutionX>
      <ImageResolutionY Unit="m">2.9898804047838085E-07</ImageResolutionY>
      <ImageSizeX>2160</ImageSizeX>
      <ImageSizeY>2160</ImageSizeY>
      <BinningX>1</BinningX>
      <BinningY>1</BinningY>
      <MaxIntensity>65535</MaxIntensity>
      <CameraType>AndorZylaCam</CameraType>
      <PositionX Unit="m">-0.000645814</PositionX>
      <PositionY Unit="m">-0.000645814</PositionY>
      <PositionZ Unit="m">5E-06</PositionZ>
      <AbsPositionZ Unit="m">0.135387495</AbsPositionZ>
      <MeasurementTimeOffset Unit="s">0</MeasurementTimeOffset>
      <AbsTime>2023-01-24T14:05:23.917+01:00</AbsTime>
      <MainExcitationWavelength Unit="nm">660</MainExcitationWavelength>
      <MainEmissionWavelength Unit="nm">723</MainEmissionWavelength>
      <ObjectiveMagnification Unit="">20</ObjectiveMagnification>
      <ObjectiveNA Unit="">1</ObjectiveNA>
      <ExposureTime Unit="s">0.02</ExposureTime>
      <OrientationMatrix>[[0.995998,0.001971,0,21.8]
```

You can see that in my XML file (first one) that it does not include "ChannelName" for the image but in the second one, it is included so I think that is why there is an error. 

My XML file comes from a Phenix 1 imaging machine. I hope this helps in finding a solution!

**Comment by jenna-tomkinson** [comment]
@sugan89 

Thank you very much for your hard work on PR #33 to fix the issues with newer Harmony XML outputs!

Since you commented recently that the current state of the PR would work with the Harmony v7 output, I attempted to try it on my end by pip installing the most recent commit into my conda environment: `git+https://github.com/broadinstitute/pe2loaddata.git@4c9aee0b9fbe74bb7308b1114dabf2895113552d`

I updated my config file to match what is included in the PR:

```
channels:
    Brightfield high: OrigBrightfield
    Alexa 488: OrigER
    Alexa 568: OrigAGP
    Alexa 647: OrigMito
    HOECHST 33342: OrigDNA
    Alexa 488 Long (CP): OrigRNA
channelid:
    1: OrigBrightfield
    2: OrigER
    3: OrigAGP
    4: OrigMito
    5: OrigDNA
    6: OrigRNA
metadata:
    Row: Row
    Col: Col
    FieldID: FieldID
    PlaneID: PlaneID
    ChannelID: ChannelID
    PositionX: PositionX
    PositionY: PositionY
    PositionZ: PositionZ
    AbsPositionZ: AbsPositionZ
```

**But when I run the command via both subprocess in Python and my bash command line, I just get the same output, which is `ChannelName` over thousands of lines. It outputs a CSV file with all of the correct columns but no rows of data at all:**

![image](https://github.com/user-attachments/assets/67c24ac4-01f8-4be2-8a9a-0391e462057c)

I am unsure what could be going wrong. I don't see where ChannelName would be included as an error and where this error is occurring in the code. I would appreciate any feedback on what could be happening or what I am missing on my end! 😄 

Again, thank you, @sugan89, for your work on getting this issue, as referenced here and in issue #32, fixed!

**Comment by sugan89** [comment]
Hi Jenna, 

Sorry I have not made the final version of the documentation part clear yet.  Could you please leave the `channels` empty in the config file and try it again. Please let me know if this helps.

**Comment by jenna-tomkinson** [comment]
Hi Suganya!

I just updated my `config` file to remove the channels content like below:

![image](https://github.com/user-attachments/assets/0b2946f0-bb00-4c02-bbbd-8e75eb8f3189)

Now it works perfectly! 🎉 Thank you so much for your quick response and assistance!

**Comment by jenna-tomkinson** [comment]
Hi @sugan89!

I am running into a new bug. The function works if I am running it via a Jupyter notebook which is great as I am using a function I created to use [subprocess with pe2loaddata](https://github.com/WayScience/pediatric_cancer_atlas_profiling/blob/main/utils/loaddata_utils.py)! I have no issues here and I get my expected output CSVs.

**But, if I try to run it as a Python script or from the terminal, I get this error:**

![image](https://github.com/user-attachments/assets/c1087c65-60b9-4058-b290-c26228c6c396)

I am unsure why I don't get this same error when running in the Jupyter notebook. Do you have any recommendations on how to get this to work as a Python script?

Thank you!

**Comment by sugan89** [comment]
Hi Jenna,

I am sorry you are facing this issue. We have not packaged the updated version of this code in PyPi yet. Probably that is why you are having this issue. We are hoping to do it sometime soon.
